spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:postgresql://localhost:5433/testdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: yourpassword
    hikari:
      allow-pool-suspension: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.boot.allow_jdbc_metadata_access: false
    open-in-view: false
  sql:
    init:
      schema-locations: schema-postgres.sql
build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
